---
title: "NCAA_Men's_Scrape"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#libaries
library(tidyverse)
library(rvest)
```

```{r}
# get the dates and sport_year ids links needed to scrape each box score link from those dates
ncaa <-
  tibble(dates = seq(as.Date('01/02/2012', format = '%m/%d/%Y'), as.Date('05/15/2012', format = '%m/%d/%Y'), by = "day"),
          ids = '10580') %>%
  add_row(dates = seq(as.Date('01/02/2013', format = '%m/%d/%Y'), as.Date('05/15/2013', format = '%m/%d/%Y'), by = "day"),
          ids = '10940') %>%
  add_row(dates = seq(as.Date('01/02/2014', format = '%m/%d/%Y'), as.Date('05/15/2014', format = '%m/%d/%Y'), by = "day"),
          ids = '11760') %>%
  add_row(dates = seq(as.Date('01/02/2015', format = '%m/%d/%Y'), as.Date('05/15/2015', format = '%m/%d/%Y'), by = "day"),
          ids = '12520') %>%
  add_row(dates = seq(as.Date('01/02/2016', format = '%m/%d/%Y'), as.Date('05/15/2016', format = '%m/%d/%Y'), by = "day"),
          ids = '12840') %>%
  add_row(dates = seq(as.Date('01/02/2017', format = '%m/%d/%Y'), as.Date('05/15/2017', format = '%m/%d/%Y'), by = "day"),
          ids = '13200') %>%
  add_row(dates = seq(as.Date('01/02/2018', format = '%m/%d/%Y'), as.Date('05/15/2018', format = '%m/%d/%Y'), by = "day"),
          ids = '13891') %>%
  add_row(dates = seq(as.Date('01/02/2019', format = '%m/%d/%Y'), as.Date('05/15/2019', format = '%m/%d/%Y'), by = "day"),
          ids = '16760') %>%
  add_row(dates = seq(as.Date('01/02/2020', format = '%m/%d/%Y'), as.Date('05/15/2020', format = '%m/%d/%Y'), by = "day"),
          ids = '17020') %>%
  mutate(page = paste0('https://stats.ncaa.org/season_divisions/', ids, '/scoreboards?utf8=%E2%9C%93&season_division_id=&game_date=', dates, '&conference_id=0&tournament_id=&commit=Submit')) %>% 
  select(page)
```

```{r}
# get box score links

get_links <- function(page) {
  page <- read_html(page)
  page %>% html_nodes('.skipMask')%>%
    html_attr("href") %>%
    as_tibble() %>%
    filter(grepl('box_score', value)) %>%
    mutate(urls = paste0('https://stats.ncaa.org', value)) %>%
    select(urls)
}

```

```{r}
# get box score links
ncaa_box_score_links <- bind_rows(map(ncaa$page, get_links))
ncaa_box_score_links <- unique(ncaa_box_score_links$urls)
```


```{r}
# scrape box score

# make function for boxscore links scrape
get_text <- function(page){
  url <- page
  page <- read_html(page)
  home_team <- page %>% html_nodes("table") %>% .[[1]] %>% html_table() %>% janitor::row_to_names(row_number =1) %>% {colnames(.)[1] = "team"; .} %>% select('team') %>% slice(1) %>% as.character()
  opponent <- page %>% html_nodes("table") %>% .[[1]] %>% html_table() %>% janitor::row_to_names(row_number =1) %>% {colnames(.)[1] = "team"; .} %>% select('team') %>% slice(2) %>% as.character()
  away_team <- page %>% html_nodes("table") %>% .[[1]] %>% html_table() %>% janitor::row_to_names(row_number =1) %>% {colnames(.)[1] = "team"; .} %>% select('team') %>% slice(2) %>% as.character()
  opponent_a <- page %>% html_nodes("table") %>% .[[1]] %>% html_table() %>% janitor::row_to_names(row_number =1) %>% {colnames(.)[1] = "team"; .} %>% select('team') %>% slice(1) %>% as.character()
  home_wins <- page %>% html_nodes("table") %>% .[[1]] %>% html_table() %>% janitor::row_to_names(row_number =1) %>% select('Total') %>% slice(1) %>% as.numeric()
  away_wins <- page %>% html_nodes("table") %>% .[[1]] %>% html_table() %>% janitor::row_to_names(row_number =1) %>% select('Total') %>% slice(2) %>% as.numeric()
 
  home_team_stats <- page %>% html_nodes("table") %>% .[[7]]  %>% html_table() %>% janitor::row_to_names(row_number =2) %>% mutate(team = home_team) %>% mutate(team_wins = home_wins) %>%  mutate(opponent = opponent) %>%   mutate(match_id = url) 
  
  away_team_stats <- page %>% html_nodes("table") %>% .[[8]]  %>% html_table() %>% janitor::row_to_names(row_number =2) %>% mutate(team = away_team) %>% mutate(team_wins = away_wins) %>%  mutate(opponent = opponent_a) %>% mutate(match_id = url) 
 
  df <- bind_rows(home_team_stats, away_team_stats)
  }


df <- map(ncaa_box_score_links[1:500], get_text) %>% bind_rows()
```


```{r}
# data wrangle cleaning so the box score is usable
box_score_df <-  df %>%
  filter(Player != 'TEAM', Player != 'Totals', !grepl('Total Team', Player), Player != 'Team') %>%
  mutate_all(na_if, '') %>%
  select(Player, S:match_id) %>%
  mutate(MS = substr(MS, 1,1) %>% as.numeric()) %>% 
  mutate(S = S %>% as.numeric()) %>% 
  mutate(Pct = Pct %>% as.numeric()) %>% 
  mutate(Assists = str_replace_all(Assists, '\\*-/', '') %>% as.numeric(),
                                        Kills = str_replace_all(Kills, '\\*-/', '') %>% as.numeric(),
                                        Errors = str_replace_all(Errors, '\\*-/', '') %>% as.numeric(),
                                        `Total Attacks` = str_replace_all(`Total Attacks`, '\\*-/', '') %>% as.numeric(),
                                        Aces = str_replace_all(Aces, '\\*-/', '') %>% as.numeric(),
                                        PTS = str_replace_all(PTS, '\\*-/', '') %>% as.numeric(),
                                        SErr = str_replace_all(SErr, '\\*-/', '') %>% as.numeric(),
                                        Digs = str_replace_all(Digs, '\\*-/', '') %>% as.numeric(),
                                        `Block Solos` = str_replace_all(`Block Solos`, '\\*-/', '') %>% as.numeric(),
                                        `Block Assists` = str_replace_all(`Block Assists`, '\\*-/', '') %>% as.numeric(),
                                        BErr = str_replace_all(BErr, '\\*-/', '') %>% as.numeric(),
                                        BHE = str_replace_all(BHE, '\\*-/', '') %>% as.numeric(),
                                        Assists = str_replace_all(Assists, '\\*', '') %>% as.numeric(),
                                        Kills = str_replace_all(Kills, '\\*', '') %>% as.numeric(),
                                        Errors = str_replace_all(Errors, '\\*', '') %>% as.numeric(),
                                        `Total Attacks` = str_replace_all(`Total Attacks`, '\\*', '') %>% as.numeric(),
                                        Aces = str_replace_all(Aces, '\\*', '') %>% as.numeric(),
                                        PTS = str_replace_all(PTS, '\\*', '') %>% as.numeric(),
                                        SErr = str_replace_all(SErr, '\\*', '') %>% as.numeric(),
                                        Digs = str_replace_all(Digs, '\\*', '') %>% as.numeric(),
                                        `Block Solos` = str_replace_all(`Block Solos`, '\\*', '') %>% as.numeric(),
                                        `Block Assists` = str_replace_all(`Block Assists`, '\\*', '') %>% as.numeric(),
                                        BErr = str_replace_all(BErr, '\\*', '') %>% as.numeric(),
                                        BHE = str_replace_all(BHE, '\\*', '') %>% as.numeric(),
                                        Assists = str_replace_all(Assists, '\\-', '') %>% as.numeric(),
                                        Kills = str_replace_all(Kills, '\\-', '') %>% as.numeric(),
                                        Errors = str_replace_all(Errors, '\\-', '') %>% as.numeric(),
                                        `Total Attacks` = str_replace_all(`Total Attacks`, '\\-', '') %>% as.numeric(),
                                        Aces = str_replace_all(Aces, '\\-', '') %>% as.numeric(),
                                        PTS = str_replace_all(PTS, '\\-', '') %>% as.numeric(),
                                        SErr = str_replace_all(SErr, '\\-', '') %>% as.numeric(),
                                        Digs = str_replace_all(Digs, '\\-', '') %>% as.numeric(),
                                        `Block Solos` = str_replace_all(`Block Solos`, '\\-', '') %>% as.numeric(),
                                        `Block Assists` = str_replace_all(`Block Assists`, '\\-', '') %>% as.numeric(),
                                        BErr = str_replace_all(BErr, '\\-', '') %>% as.numeric(),
                                        BHE = str_replace_all(BHE, '\\-', '') %>% as.numeric(),
                                        Assists = str_replace_all(Assists, '\\/', '') %>% as.numeric(),
                                        Kills = str_replace_all(Kills, '\\/', '') %>% as.numeric(),
                                        Errors = str_replace_all(Errors, '\\/', '') %>% as.numeric(),
                                        `Total Attacks` = str_replace_all(`Total Attacks`, '\\/', '') %>% as.numeric(),
                                        Aces = str_replace_all(Aces, '\\/', '') %>% as.numeric(),
                                        PTS = str_replace_all(PTS, '\\/', '') %>% as.numeric(),
                                        SErr = str_replace_all(SErr, '\\/', '') %>% as.numeric(),
                                        Digs = str_replace_all(Digs, '\\/', '') %>% as.numeric(),
                                        `Block Solos` = str_replace_all(`Block Solos`, '\\/', '') %>% as.numeric(),
                                        `Block Assists` = str_replace_all(`Block Assists`, '\\/', '') %>% as.numeric(),
                                        BErr = str_replace_all(BErr, '\\/', '') %>% as.numeric(),
                                        BHE = str_replace_all(BHE, '\\/', '') %>% as.numeric(),
                                        Assists = str_replace_all(Assists, '\\-/', '') %>% as.numeric(),
                                        Kills = str_replace_all(Kills, '\\-/', '') %>% as.numeric(),
                                        Errors = str_replace_all(Errors, '\\-/', '') %>% as.numeric(),
                                        `Total Attacks` = str_replace_all(`Total Attacks`, '\\-/', '') %>% as.numeric(),
                                        Aces = str_replace_all(Aces, '\\-/', '') %>% as.numeric(),
                                        Aces = str_replace_all(Aces, '\\-/', '') %>% as.numeric(),
                                        PTS = str_replace_all(PTS, '\\-/', '') %>% as.numeric(),
                                        SErr = str_replace_all(SErr, '\\-/', '') %>% as.numeric(),
                                        Digs = str_replace_all(Digs, '\\-/', '') %>% as.numeric(),
                                        `Block Solos` = str_replace_all(`Block Solos`, '\\-/', '') %>% as.numeric(),
                                        `Block Assists` = str_replace_all(`Block Assists`, '\\-/', '') %>% as.numeric(),
                                        BErr = str_replace_all(BErr, '\\-/', '') %>% as.numeric(),
                                        BHE = str_replace_all(BHE, '\\-/', '') %>% as.numeric())
```
